// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: BushidoPadPro_UI

#ifndef _UI_COMP_AAA_H
#define _UI_COMP_AAA_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT aaa
#define UI_COMP_AAA_AAA 0
#define _UI_COMP_AAA_NUM 1
lv_obj_t *ui_aaa_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
