// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: BushidoPadPro_UI

#ifndef _BUSHIDOPADPRO_UI_UI_COMP_HOOK_H
#define _BUSHIDOPADPRO_UI_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_aaa_create_hook( lv_obj_t *comp );
void ui_comp_imgAllenamento_create_hook( lv_obj_t *comp );

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
