// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: BushidoPadPro_UI

#include "../ui.h"

// COMPONENT aaa

lv_obj_t *ui_aaa_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_aaa;
cui_aaa = lv_btn_create(comp_parent);
lv_obj_set_width( cui_aaa, lv_pct(20));
lv_obj_set_height( cui_aaa, lv_pct(60));
lv_obj_set_x( cui_aaa, -207 );
lv_obj_set_y( cui_aaa, 28 );
lv_obj_set_align( cui_aaa, LV_ALIGN_CENTER );
lv_obj_add_state( cui_aaa, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( cui_aaa, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_aaa, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_AAA_NUM);
children[UI_COMP_AAA_AAA] = cui_aaa;
lv_obj_add_event_cb(cui_aaa, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_aaa, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_aaa_create_hook(cui_aaa);
return cui_aaa; 
}

