// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: BushidoPadPro_UI

#include "../ui.h"

// COMPONENT imgAllenamento

lv_obj_t *ui_imgAllenamento_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_imgAllenamento;
cui_imgAllenamento = lv_img_create(comp_parent);
lv_obj_set_width( cui_imgAllenamento, 24);
lv_obj_set_height( cui_imgAllenamento, 24);
lv_obj_set_x( cui_imgAllenamento, 0 );
lv_obj_set_y( cui_imgAllenamento, 10 );
lv_obj_set_align( cui_imgAllenamento, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_imgAllenamento, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_imgAllenamento, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_IMGALLENAMENTO_NUM);
children[UI_COMP_IMGALLENAMENTO_IMGALLENAMENTO] = cui_imgAllenamento;
lv_obj_add_event_cb(cui_imgAllenamento, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_imgAllenamento, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_imgAllenamento_create_hook(cui_imgAllenamento);
return cui_imgAllenamento; 
}

