// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: BushidoPadPro_UI

#ifndef _UI_COMP_IMGALLENAMENTO_H
#define _UI_COMP_IMGALLENAMENTO_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT imgAllenamento
#define UI_COMP_IMGALLENAMENTO_IMGALLENAMENTO 0
#define _UI_COMP_IMGALLENAMENTO_NUM 1
lv_obj_t *ui_imgAllenamento_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
