// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: BushidoPadPro_UI

#include "../ui.h"

lv_obj_t *uic_imgImpostazioni;
lv_obj_t *uic_imgWifi;
lv_obj_t *uic_HOME;
lv_obj_t *ui_HOME = NULL;lv_obj_t *ui_topbar = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_lblUser = NULL;lv_obj_t *ui_ImgAudion = NULL;lv_obj_t *ui_Switch2 = NULL;lv_obj_t *ui_mainarea = NULL;lv_obj_t *ui_btnallenamento = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_imgAllenamento = NULL;lv_obj_t *ui_btnallenamento1 = NULL;lv_obj_t *ui_DISPOSITIVO = NULL;lv_obj_t *ui_imgDispositivo = NULL;lv_obj_t *ui_btnallenamento2 = NULL;lv_obj_t *ui_WIFI = NULL;lv_obj_t *ui_ImgWifi = NULL;lv_obj_t *ui_btnallenamento3 = NULL;lv_obj_t *ui_IMPOSTAZIONI = NULL;lv_obj_t *ui_Imgimpostazioni = NULL;
// event funtions

// build funtions

void ui_HOME_screen_init(void)
{
ui_HOME = lv_obj_create(NULL);
lv_obj_clear_flag( ui_HOME, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_bg_color(ui_HOME, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HOME, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_topbar = lv_obj_create(ui_HOME);
lv_obj_remove_style_all(ui_topbar);
lv_obj_set_height( ui_topbar, 40);
lv_obj_set_width( ui_topbar, lv_pct(100));
lv_obj_set_flex_flow(ui_topbar,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_topbar, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_topbar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_topbar, lv_color_hex(0x323131), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_topbar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_topbar, lv_color_hex(0xFC0606), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_topbar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_topbar, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_topbar, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_topbar);
lv_obj_set_width( ui_Label2, lv_pct(37));
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 44
lv_obj_set_x( ui_Label2, 105 );
lv_obj_set_y( ui_Label2, -136 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Label2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Label2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_long_mode(ui_Label2,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_Label2,"BUSHIDO Pad PRO");
lv_obj_add_flag( ui_Label2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Label2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label2, lv_color_hex(0x130101), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Label2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Label2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Label2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_Label2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_Label2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label2, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblUser = lv_label_create(ui_topbar);
lv_obj_set_width( ui_lblUser, 222);
lv_obj_set_height( ui_lblUser, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblUser, -164 );
lv_obj_set_y( ui_lblUser, -142 );
lv_obj_set_align( ui_lblUser, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_lblUser,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_lblUser, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_lblUser,"OSPITE");
lv_obj_set_style_text_font(ui_lblUser, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblUser, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblUser, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblUser, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblUser, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgAudion = lv_img_create(ui_topbar);
lv_img_set_src(ui_ImgAudion, &ui_img_imgaudio_png);
lv_obj_set_width( ui_ImgAudion, LV_SIZE_CONTENT);  /// 28
lv_obj_set_height( ui_ImgAudion, LV_SIZE_CONTENT);   /// 28
lv_obj_set_x( ui_ImgAudion, 169 );
lv_obj_set_y( ui_ImgAudion, -141 );
lv_obj_set_align( ui_ImgAudion, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImgAudion, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImgAudion, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Switch2 = lv_switch_create(ui_topbar);
lv_obj_set_width( ui_Switch2, 46);
lv_obj_set_height( ui_Switch2, 25);
lv_obj_set_align( ui_Switch2, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Switch2, LV_STATE_CHECKED );     /// States
lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x6A6464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x09AE4E), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_Switch2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_Switch2, 255, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_border_color(ui_Switch2, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Switch2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_mainarea = lv_obj_create(ui_HOME);
lv_obj_remove_style_all(ui_mainarea);
lv_obj_set_height( ui_mainarea, 280);
lv_obj_set_width( ui_mainarea, lv_pct(100));
lv_obj_set_x( ui_mainarea, 0 );
lv_obj_set_y( ui_mainarea, 40 );
lv_obj_set_flex_flow(ui_mainarea,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_mainarea, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( ui_mainarea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnallenamento = lv_btn_create(ui_mainarea);
lv_obj_set_width( ui_btnallenamento, lv_pct(45));
lv_obj_set_height( ui_btnallenamento, lv_pct(35));
lv_obj_set_x( ui_btnallenamento, -203 );
lv_obj_set_y( ui_btnallenamento, 131 );
lv_obj_set_align( ui_btnallenamento, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_btnallenamento,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_btnallenamento, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_btnallenamento, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnallenamento, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnallenamento, lv_color_hex(0x8B0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnallenamento, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_btnallenamento, lv_color_hex(0xA6A6A6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_btnallenamento, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_btnallenamento, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_btnallenamento, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_btnallenamento, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_btnallenamento, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnallenamento, lv_color_hex(0x6F0000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_btnallenamento, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label1 = lv_label_create(ui_btnallenamento);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Label1, 0 );
lv_obj_set_y( ui_Label1, -10 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"ALLENAMENTO");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imgAllenamento = lv_img_create(ui_btnallenamento);
lv_img_set_src(ui_imgAllenamento, &ui_img_imgallenamento_png);
lv_obj_set_height( ui_imgAllenamento, 25);
lv_obj_set_width( ui_imgAllenamento, LV_SIZE_CONTENT);  /// 22
lv_obj_set_x( ui_imgAllenamento, 0 );
lv_obj_set_y( ui_imgAllenamento, 10 );
lv_obj_set_align( ui_imgAllenamento, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_imgAllenamento,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_imgAllenamento, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_imgAllenamento, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgAllenamento, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnallenamento1 = lv_btn_create(ui_mainarea);
lv_obj_set_width( ui_btnallenamento1, lv_pct(45));
lv_obj_set_height( ui_btnallenamento1, lv_pct(35));
lv_obj_set_x( ui_btnallenamento1, -203 );
lv_obj_set_y( ui_btnallenamento1, 131 );
lv_obj_set_align( ui_btnallenamento1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_btnallenamento1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_btnallenamento1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_btnallenamento1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnallenamento1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnallenamento1, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnallenamento1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_btnallenamento1, lv_color_hex(0xA6A6A6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_btnallenamento1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_btnallenamento1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_btnallenamento1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_btnallenamento1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_btnallenamento1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnallenamento1, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_btnallenamento1, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_DISPOSITIVO = lv_label_create(ui_btnallenamento1);
lv_obj_set_width( ui_DISPOSITIVO, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_DISPOSITIVO, LV_SIZE_CONTENT);   /// 100
lv_obj_set_align( ui_DISPOSITIVO, LV_ALIGN_CENTER );
lv_label_set_text(ui_DISPOSITIVO,"DISPOSITIVO");
lv_obj_set_style_text_font(ui_DISPOSITIVO, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imgDispositivo = lv_img_create(ui_btnallenamento1);
lv_img_set_src(ui_imgDispositivo, &ui_img_imgdispositivo_png);
lv_obj_set_height( ui_imgDispositivo, 25);
lv_obj_set_width( ui_imgDispositivo, LV_SIZE_CONTENT);  /// 22
lv_obj_set_align( ui_imgDispositivo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgDispositivo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgDispositivo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnallenamento2 = lv_btn_create(ui_mainarea);
lv_obj_set_width( ui_btnallenamento2, lv_pct(45));
lv_obj_set_height( ui_btnallenamento2, lv_pct(35));
lv_obj_set_x( ui_btnallenamento2, -203 );
lv_obj_set_y( ui_btnallenamento2, 131 );
lv_obj_set_align( ui_btnallenamento2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_btnallenamento2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_btnallenamento2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_btnallenamento2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnallenamento2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnallenamento2, lv_color_hex(0x1565C0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnallenamento2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_btnallenamento2, lv_color_hex(0xA6A6A6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_btnallenamento2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_btnallenamento2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_btnallenamento2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_btnallenamento2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_btnallenamento2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnallenamento2, lv_color_hex(0x0D47A1), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_btnallenamento2, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_WIFI = lv_label_create(ui_btnallenamento2);
lv_obj_set_width( ui_WIFI, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_WIFI, LV_SIZE_CONTENT);   /// 100
lv_obj_set_align( ui_WIFI, LV_ALIGN_CENTER );
lv_label_set_text(ui_WIFI,"WIFI");
lv_obj_set_style_text_font(ui_WIFI, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImgWifi = lv_img_create(ui_btnallenamento2);
lv_img_set_src(ui_ImgWifi, &ui_img_imgwifi_png);
lv_obj_set_height( ui_ImgWifi, 25);
lv_obj_set_width( ui_ImgWifi, LV_SIZE_CONTENT);  /// 24
lv_obj_set_x( ui_ImgWifi, -127 );
lv_obj_set_y( ui_ImgWifi, 84 );
lv_obj_set_align( ui_ImgWifi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImgWifi, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImgWifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnallenamento3 = lv_btn_create(ui_mainarea);
lv_obj_set_width( ui_btnallenamento3, lv_pct(45));
lv_obj_set_height( ui_btnallenamento3, lv_pct(35));
lv_obj_set_x( ui_btnallenamento3, -203 );
lv_obj_set_y( ui_btnallenamento3, 131 );
lv_obj_set_align( ui_btnallenamento3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_btnallenamento3,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_btnallenamento3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_btnallenamento3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnallenamento3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnallenamento3, lv_color_hex(0xF57C00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnallenamento3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_btnallenamento3, lv_color_hex(0xA6A6A6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_btnallenamento3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_btnallenamento3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_btnallenamento3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_btnallenamento3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_btnallenamento3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnallenamento3, lv_color_hex(0xBB5A00), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_btnallenamento3, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_IMPOSTAZIONI = lv_label_create(ui_btnallenamento3);
lv_obj_set_width( ui_IMPOSTAZIONI, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_IMPOSTAZIONI, LV_SIZE_CONTENT);   /// 100
lv_obj_set_align( ui_IMPOSTAZIONI, LV_ALIGN_CENTER );
lv_label_set_text(ui_IMPOSTAZIONI,"IMPOSTAZIONI");
lv_obj_set_style_text_font(ui_IMPOSTAZIONI, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Imgimpostazioni = lv_img_create(ui_btnallenamento3);
lv_img_set_src(ui_Imgimpostazioni, &ui_img_imgimpostazioni_png);
lv_obj_set_height( ui_Imgimpostazioni, 25);
lv_obj_set_width( ui_Imgimpostazioni, LV_SIZE_CONTENT);  /// 24
lv_obj_set_x( ui_Imgimpostazioni, 107 );
lv_obj_set_y( ui_Imgimpostazioni, 81 );
lv_obj_set_align( ui_Imgimpostazioni, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Imgimpostazioni, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Imgimpostazioni, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_HOME = ui_HOME;
uic_imgWifi = ui_ImgWifi;
uic_imgImpostazioni = ui_Imgimpostazioni;

}

void ui_HOME_screen_destroy(void)
{
   if (ui_HOME) lv_obj_del(ui_HOME);

// NULL screen variables
uic_HOME= NULL;
ui_HOME= NULL;
ui_topbar= NULL;
ui_Label2= NULL;
ui_lblUser= NULL;
ui_ImgAudion= NULL;
ui_Switch2= NULL;
ui_mainarea= NULL;
ui_btnallenamento= NULL;
ui_Label1= NULL;
ui_imgAllenamento= NULL;
ui_btnallenamento1= NULL;
ui_DISPOSITIVO= NULL;
ui_imgDispositivo= NULL;
ui_btnallenamento2= NULL;
ui_WIFI= NULL;
uic_imgWifi= NULL;
ui_ImgWifi= NULL;
ui_btnallenamento3= NULL;
ui_IMPOSTAZIONI= NULL;
uic_imgImpostazioni= NULL;
ui_Imgimpostazioni= NULL;

}
