// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: BushidoPadPro_UI

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HOME
extern void ui_HOME_screen_init(void);
extern void ui_HOME_screen_destroy(void);
extern lv_obj_t *ui_HOME;
extern lv_obj_t *ui_topbar;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_lblUser;
extern lv_obj_t *ui_ImgAudion;
extern lv_obj_t *ui_Switch2;
extern lv_obj_t *ui_mainarea;
extern lv_obj_t *ui_btnallenamento;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_imgAllenamento;
extern lv_obj_t *ui_btnallenamento1;
extern lv_obj_t *ui_DISPOSITIVO;
extern lv_obj_t *ui_imgDispositivo;
extern lv_obj_t *ui_btnallenamento2;
extern lv_obj_t *ui_WIFI;
extern lv_obj_t *ui_ImgWifi;
extern lv_obj_t *ui_btnallenamento3;
extern lv_obj_t *ui_IMPOSTAZIONI;
extern lv_obj_t *ui_Imgimpostazioni;
// CUSTOM VARIABLES
extern lv_obj_t *uic_HOME;
extern lv_obj_t *uic_imgWifi;
extern lv_obj_t *uic_imgImpostazioni;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

