// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: BushidoPadPro_UI

#include "../ui.h"

lv_obj_t *ui_SPLASH = NULL;lv_obj_t *ui_logoteclab = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Bar2 = NULL;
// event funtions

// build funtions

void ui_SPLASH_screen_init(void)
{
ui_SPLASH = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SPLASH, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SPLASH, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SPLASH, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_logoteclab = lv_img_create(ui_SPLASH);
lv_img_set_src(ui_logoteclab, &ui_img_logoteclab_png);
lv_obj_set_width( ui_logoteclab, LV_SIZE_CONTENT);  /// 300
lv_obj_set_height( ui_logoteclab, LV_SIZE_CONTENT);   /// 244
lv_obj_set_x( ui_logoteclab, 0 );
lv_obj_set_y( ui_logoteclab, -17 );
lv_obj_set_align( ui_logoteclab, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_logoteclab, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_logoteclab, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_SPLASH);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -199 );
lv_obj_set_y( ui_Label3, 127 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Version 2.1.1");
lv_obj_set_style_text_decor(ui_Label3, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_SPLASH);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -169 );
lv_obj_set_y( ui_Label4, 112 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Smart Combat Training");
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar2 = lv_bar_create(ui_SPLASH);
lv_bar_set_value(ui_Bar2,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar2, 150);
lv_obj_set_height( ui_Bar2, 10);
lv_obj_set_x( ui_Bar2, -1 );
lv_obj_set_y( ui_Bar2, 131 );
lv_obj_set_align( ui_Bar2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Bar2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x989494), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_SPLASH_screen_destroy(void)
{
   if (ui_SPLASH) lv_obj_del(ui_SPLASH);

// NULL screen variables
ui_SPLASH= NULL;
ui_logoteclab= NULL;
ui_Label3= NULL;
ui_Label4= NULL;
ui_Bar2= NULL;

}
