// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: BushidoPadPro_UI

#ifndef _BUSHIDOPADPRO_UI_UI_H
#define _BUSHIDOPADPRO_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_SPLASH.h"
#include "screens/ui_HOME.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_logoteclab_png);   // assets/logoteclab.png
LV_IMG_DECLARE( ui_img_imgaudio_png);   // assets/imgAudio.png
LV_IMG_DECLARE( ui_img_imgallenamento_png);   // assets/imgAllenamento.png
LV_IMG_DECLARE( ui_img_imgdispositivo_png);   // assets/imgDispositivo.png
LV_IMG_DECLARE( ui_img_imgwifi_png);   // assets/imgWifi.png
LV_IMG_DECLARE( ui_img_imgimpostazioni_png);   // assets/imgImpostazioni.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
